### ISSUE TITLE
 Old APK 

### ISSUE THREAD

**Issue by 89z** [kagasu/GooglePlayStoreApi#14]
Is it possible to get old APK from this package, or just latest version? Similar to this:

https://www.apkmirror.com/uploads/?q=github-2

**Comment by kagasu** [comment]
Set specific `versionCode` you want.
Not tested.

https://github.com/kagasu/GooglePlayStoreApi/blob/5bea3004398fb931bfdd6b471c848da01f6162c6/GooglePlayStoreApi/GooglePlayStoreClient.cs#L196

**Comment by 89z** [comment]
Is it possible to list the available versions?
