### ISSUE TITLE
Not download Unreleased apps

### ISSUE THREAD

**Issue by rezionline** [kagasu/GooglePlayStoreApi#2]
Thank you very much for your great script. I want to say something that will make the script work more complete, And it's possible to download (Unreleased) apps and games. Please make this possible. Thank you

**Comment by kagasu** [comment]
can't.
we can't download unreleased apps.
because that app is "unreleased".

**Comment by rezionline** [comment]
But it can be downloaded with the phone from the Google Play Store app
