### ISSUE TITLE
Getting Forbidden 403 Error When Try Get Token

### ISSUE THREAD

**Issue by rezionline** [kagasu/GooglePlayStoreApi#5]
Hi, When i try to get token from 'https://android.clients.google.com' with correct user name and password server return 403 Error.

I am use link below code : https://github.com/kagasu/GooglePlayStoreApi/blob/master/GooglePlayStoreApi/GooglePlayStoreClient.cs

This problem happened two days ago. Where is the problem and how can it be resolved?

**Comment by kagasu** [comment]
Everything similar to this project was died at same time.
this mean,  google decided reject old API, i think.

so, we have to re-implement new `GetGoogleToken` API.

**Comment by rezionline** [comment]
What alternative should we use now? And where can I access to new Google Play APIs?

**Comment by kagasu** [comment]
I'm released new version `1.0.3` now.
Please check again [README.md](https://github.com/kagasu/GooglePlayStoreApi/blob/master/README.md)

**Comment by rezionline** [comment]
Thank you, but there is no better way to do it more professionally and automatically like before?

**Comment by kagasu** [comment]
We have to get `auth_token`  from website at first time.
That website is complex, so i don't want to implement it.
If you want automatically get `auth_token`, write code your way using like `Headless Chrome`.

Also, `GoogleToken` looks like doesn't have expiry.
It is reusable.

### First login
```cs
var token = "oauth2_4/...";
token = await client.GetGoogleToken(token);
// save token to "token.txt"
File.WriteAllText("token.txt", token);
await client.GetGoogleAuth(token);
```

### Second login
```cs
// load token from "token.txt"
var token = File.ReadAllText("token.txt");
await client.GetGoogleAuth(token);
```

**Comment by hoffie** [comment]
You may gain further insight from the analyses in this issue: https://github.com/NoMore201/googleplay-api/issues/98
